### ISSUE TITLE
do we need nb2w dependency here?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-graph-vis#14]
https://github.com/oda-hub/renku-graph-vis/blob/7266088fb2b6b1700d2851eebec8f62b74d1d78c/setup.py#L25

**Comment by burnout87** [comment]
No it's no longer needed, after the split in two plugins from `reknu-aqs`. It should be only inside `renu-aqs-annotation`.

**Comment by burnout87** [comment]
And based on this issue, #9 should be adjusted accordingly
