### ISSUE TITLE
Move oda annotation writing to a separate plugin ?

### ISSUE THREAD

**Issue by burnout87** [oda-hub/renku-graph-vis#2]
Currently, the two functionalities are implemented within the plugin:

- graph visualization: interactive in the browser (to be used also within a renkulab session) and png image
- oda annotations during notebooks execution - for now, the `aqsconverter` is used, and the `sitecustomize.py` file is used to trigger the logging of the oda annotations

the second functionality should now be moved to a separate specific plugin, as it is different from the main purpose of this new plugin and strictly bound to oda-related knowledge (also the `inspect` should be part of it)

EDIT: alternatively: make the logging of additional annotations configurable:
- make it configurable so that the necessary library to import (eg `aqsconvertes`, `astroquery`, `nb2workflow`) are specified in some config
- make the content of the `sitecustomize.py` file configurable
- make also the `inspect` behavior configurable? for the moment it uses `nb2workflow`

**Comment by burnout87** [comment]
https://github.com/oda-hub/renku-oda-annotation

**Comment by volodymyrss** [comment]
can you please put some references here?

**Comment by burnout87** [comment]
Implemented the following plugins:
* `renku-graph-vis`: for graph visualization, interactive in the browser and in a renkulab session, and png image
* `renku-aqs-annotation`: log oda annotations during notebooks execution [plugin](https://github.com/oda-hub/renku-aqs-annotation)
