### ISSUE TITLE
add a "make suggestion" button

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-graph-vis#5]
# Advances Domain

Mention the Domain this issue addresses, e.g.: 

* UX
* resilience
* community-expanding feature

**Comment by burnout87** [comment]
During #1 , should an issue here be opened?

![image](https://github.com/oda-hub/renku-graph-vis/assets/3757833/962edbcb-4089-4594-a1e3-7a3f881d5343)

**Comment by burnout87** [comment]
@volodymyrss

**Comment by burnout87** [comment]
The buttons opens an issue in this repo with the label "graph suggestion" on https://github.com/oda-hub/renku-aqs-graph-library

![image](https://github.com/oda-hub/renku-graph-vis/assets/3757833/f7eb1c03-c9ef-4052-8ada-d695554a7168)
